version: '3.8'

services:
  backend_django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    # volumes:
    #   - ./django_vol/:/home/worker/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev

  frontend_react:
    build: ./frontend
    ports:
      - 3000:80
      - 443:443
    depends_on:
      - backend_django
    volumes:
      - ./.certbot/www:/var/www/certbot/:ro
      - ./.certbot/conf/:/etc/nginx/ssl/:ro

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./.certbot/www/:/var/www/certbot/:rw
      - ./.certbot/conf/:/etc/letsencrypt/:rw