version: '3.8'

services:
  backend_django:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static

    ports:
    - 8000:8000
    env_file:
      - ./.env.prod

  frontend_react:
    build: ./frontend
    volumes:
      - static_volume:/home/app/web/static
      - ./.certbot/www:/var/www/certbot/:ro
      - ./.certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - 3000:80
      - 443:443
    depends_on:
      - backend_django
    
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./.certbot/www/:/var/www/certbot/:rw
      - ./.certbot/conf/:/etc/letsencrypt/:rw

volumes:
  static_volume: