version: '3.8'

services:
  backend_django:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    # command: python manage.py runserver 0.0.0.0:8000
    # volumes:
    #   - ./django_vol/:/home/worker/
    expose:
    - 8000
    env_file:
      - ./.env.prod

  frontend_react:
    build: ./frontend
    ports:
      - 3000:80
    depends_on:
      - backend_django